Finestra Miner branding requirements added.
helium/hotspot-app pull request #464
Opened 2021-04-09 21:27 UTC by encku

2021-04-12 23:10 UTC, tyler-whitman commented
Once you have a maker account you will also need to add your support email here https://github.com/helium/hotspot-app/blob/main/src/utils/stakingClient.ts#L55

2021-04-12 23:12 UTC, tyler-whitman approved these changes
Code looks good and is working as expected, just missing the support email once you have a maker ID. 

I will wait for one other approver as well.

2021-04-12 23:32 UTC, cokes518 commented
FYI, we'll merge this to main when community has approved Smart Mimic as a Maker.

2021-04-16 16:57 UTC, tyler-whitman requested changes
Once you have a maker account you will also need to add your support email here https://github.com/helium/hotspot-app/blob/main/src/utils/stakingClient.ts#L55

2021-04-20 22:22 UTC, cokes518 commented
As part of assert_v2, you will also want to add your Hotspot and its default antenna dBi:
https://github.com/helium/hotspot-app/blob/da5fbce2608fb3a23347ffbde556d2829dce9f29/src/components/HotspotConfigurationPicker.tsx#L26

and the EN string
https://github.com/helium/hotspot-app/blob/da5fbce2608fb3a23347ffbde556d2829dce9f29/src/locales/en.ts#L959

2021-04-20 23:39 UTC, tyler-whitman requested changes
Thanks for adding the support email. The last change would be the antenna info with Assert V2 that Coco mentioned

2021-04-21 21:40 UTC, tyler-whitman commented
You can reference https://github.com/helium/hotspot-app/pull/497 for the antenna changes

2021-05-13 03:23 UTC, encku commented
> You can reference #497 for the antenna changes



> Thanks for adding the support email. The last change would be the antenna info with Assert V2 that Coco mentioned. Since this is a new change. I can also do it for you if you give me the values you would like me to add.

#497 completed.

2021-05-21 18:51 UTC, cokes518 commented
@tyler-whitman this can be merged

2021-05-24 21:32 UTC, tyler-whitman requested changes

2021-05-24 21:32 UTC, tyler-whitman commented on src/components/HotspotConfigurationPicker.tsx
> +export type AntennaId =
You need to remove these lines, 18 - 48.

They got moved to the `constants/antennas` file

2021-05-24 21:32 UTC, tyler-whitman commented on src/components/HotspotPairingList.tsx
> +  'Finestra Miner': (
Finestra should be below LongAP please. We keep them in the order they were added.

2021-05-24 21:32 UTC, tyler-whitman commented on src/components/HotspotConfigurationPicker.tsx
> +  | 'finestra_us'
You need to move this to https://github.com/helium/hotspot-app/blob/main/src/constants/antennas.ts#L13

2021-05-24 21:32 UTC, tyler-whitman commented on src/components/HotspotConfigurationPicker.tsx
> +  finestra_us: { id: 'finestra_us', gain: 1.2 },
You need to move this to https://github.com/helium/hotspot-app/blob/main/src/constants/antennas.ts#L30

2021-05-28 02:15 UTC, tyler-whitman requested changes

2021-05-28 02:15 UTC, tyler-whitman commented on src/features/hotspots/setup/HotspotSelectionListItem.tsx
> +      case 'Finestra':
I must have missed this one, sorry one last change this needs to be below `LONGAPONE`

2021-05-28 02:15 UTC, tyler-whitman commented on src/features/hotspots/setup/HotspotSetupDiagnosticsScreen.tsx
> +      case 'Finestra':
Same with this one

2021-05-28 17:55 UTC, tyler-whitman commented
I made some fixes so I opened it as another PR. https://github.com/helium/hotspot-app/pull/619

2021-05-28 17:55 UTC, tyler-whitman commented
I made some fixes so I opened it as another PR. https://github.com/helium/hotspot-app/pull/619

2021-05-28 17:55 UTC, closed without merging