update copy
helium/hotspot-app pull request #514
Opened 2021-04-26 15:40 UTC by cokes518

removes learn more links that go nowhere.

2021-04-26 16:50 UTC, matthewcarlreetz approved these changes

2021-04-26 16:52 UTC, matthewcarlreetz approved these changes
💯

2021-04-26 17:43 UTC, tyler-whitman requested changes

2021-04-26 17:43 UTC, tyler-whitman commented on src/features/wallet/scan/ScanView.tsx
> +                <Text variant="body2Bold" color="blueMain" />
We can actually just remove these Text elements entirely if they are no longer being used.

2021-04-28 18:10 UTC, tyler-whitman approved these changes

2021-04-28 22:16 UTC, merged