Add deep links and simplify hotspot tab
helium/hotspot-app pull request #518
Opened 2021-04-28 17:43 UTC by matthewcarlreetz

Parse deep links
Create LinkProvider.
Refactor ScanView parse and nav logic to LinkProvider-useLink.
Slim down to single bottom sheet.

2021-04-28 23:43 UTC, tyler-whitman requested changes
The deep link doesnt work when I havent enabled map location permissions. I get stuck on a white screen with the tabs there and I never see the lock screen.

2021-04-28 23:43 UTC, tyler-whitman commented on src/utils/useMount.tsx
> +export default (effect: EffectCallback) => useEffect(effect, [])
Nice, I like it

2021-04-28 23:43 UTC, tyler-whitman commented on src/features/hotspots/root/HotspotsView.tsx
> +          animatedPosition={animatedIndex}
The animation for the witness button flickers heavily when you go from the full screen map to selecting a hotspot now

2021-04-29 12:10 UTC, matthewcarlreetz commented on src/utils/animateTransition.ts
> +    console.log('animateTransition:', { id, enabledOnAndroid })
I added an env var to enable these logs. They're super useful for debugging, but I agree they're annoying when you don't want them.

2021-04-29 18:47 UTC, matthewcarlreetz commented on src/providers/LinkProvider.tsx
> +      const scanResult = parseBarCodeData(data, scanType)
If they scan a poorly formed qr outside the app, it will just fail silently

2021-04-29 18:48 UTC, matthewcarlreetz commented on src/providers/LinkProvider.tsx
> +      const scanResult = parseBarCodeData(data, scanType)
If they are using our internal scanner, it send a "failed" haptic and let you retry after 2 seconds.

2021-04-29 18:49 UTC, matthewcarlreetz commented on src/providers/LinkProvider.tsx
> +    if (parsed.url !== 'helium://app') return
If it didn't match this format, they are likely scanning a payment, burn, or account and it will continue on

2021-04-29 18:49 UTC, matthewcarlreetz commented on src/providers/LinkProvider.tsx
> +    if (parsed.url !== 'helium://app') return
if it's an unrecognized qr, it will just give you a failure haptic

2021-04-29 21:47 UTC, tyler-whitman approved these changes
Looks good!

2021-04-30 01:05 UTC, merged