Deployment Mode
helium/hotspot-app pull request #606
Opened 2021-05-22 18:14 UTC by MichaelBrew

Feature request: https://github.com/helium/hotspot-app/issues/132

## Summary
Add support for "Deployment Mode" in Settings. Enabling Deployment Mode will permanently disable the ability to view secret words unless the user signs out and imports their account again.

## Screenshots
Demo: https://www.dropbox.com/s/mpccmbvcyresw41/hotspot_deployment_mode.mov?dl=0
| Disabled | Confirmation | Enabled |
| ---- | ---- | ---- |
| ![Snip20210516_29](https://user-images.githubusercontent.com/3493682/118413790-aec50900-b666-11eb-962d-7864c63baee0.png) | ![Snip20210516_30](https://user-images.githubusercontent.com/3493682/118413796-b4baea00-b666-11eb-8a31-e01098b52054.png) | ![Snip20210516_31](https://user-images.githubusercontent.com/3493682/118413798-b97f9e00-b666-11eb-921b-7ef551f3ccde.png) |

## Implementation
Deployment Mode relies on the `secureAccount` util to enable, disable, and restore state from the local device. The secure item state is imported and subsequently managed by `appSlice`.

## i18n
The following strings have been added (with the help of Google Translate):
- title: 'Deployment Mode',
- enableButton: 'Enable Deployment Mode',
- description: 'Deployment mode will disable the option to view your secret words.',
- warning: 'This can only be disabled by logging out and reimporting your account.',

### TODO
- [x] Fix bug where "Enable Deployment Mode" switch value is false when actually enabled after restoring on app init
- [x] Refactor shared logic between `DeploymentModeModal` and `HeliumActionSheet`
  - Ended up creating a `HeliumBottomSheet` component that's utilized by `DeploymentModeModal` with the opportunity to be used in `HeliumActionSheet` at some point

2021-05-22 18:15 UTC, MichaelBrew commented
Apologies for all the old commits from a previous PR - I branched off that before it was merged to main, but the file diff here looks accurate

2021-05-25 20:04 UTC, cokes518 commented
Hey @MichaelBrew nice PR! Looking at the rationale behind the feature request, since it was written in February and seems like a lifetime ago, we've actually added a lot of host/owner features that seems to negate the need for a deployment mode (as spec'd out in this PR, with the intention to just hide 12 words). 

As an example, there's no need to pass on the app to a host to assert (and thus hide the words) since there's now remote assert support.

There's also no need to pass the phone to a host to run diagnostics (and thus to hide the words) since hosts can follow a hotspot and run diagnostics on their own phone.

I think the key part of deployment mode then, is restricting damaging and irreversible actions *in addition to revealing the 12 words*. Enabled deployment mode doesn't matter much if you can still empty the wallet and transfer all the hotspots out of the account.

We can scope out this PR to include restricting payment transactions (any payment transaction that debits the account) and hotspot transfers, and renaming it to "Secure Mode", it can capture the spirit of deployment mode a bit more, with additional security features in mind. 

What do you think?

2021-05-25 23:26 UTC, tyler-whitman commented
Thanks for submitting another great change! We will get to this review soon, just finishing up some changes for our next release and then we can get this in for the following one I think.

2021-06-18 16:09 UTC, MichaelBrew commented
Hey @cokes518 just want to check back in and see if you have any more thoughts about this PR and https://github.com/MichaelBrew/hotspot-app/pull/2? Open to feedback if we want to tweak any of presentation / feature language / functionality.

2021-06-18 17:06 UTC, cokes518 commented
> Hey @cokes518 just want to check back in and see if you have any more thoughts about this PR and [MichaelBrew#2](https://github.com/MichaelBrew/hotspot-app/pull/2)? Open to feedback if we want to tweak any of presentation / feature language / functionality.

hey @MichaelBrew! I'd love to see #2 merged with this one and shipped as a single feature.

2021-06-18 17:30 UTC, MichaelBrew commented
@cokes518 ok sure thing, I'll go ahead and merge those into a single PR here 👍

2021-07-23 15:50 UTC, cokes518 commented
@MichaelBrew We're doing the final reviews and it seems there is a feature-gap where a user in deployment mode can transfer Hotspots out of the account. 

Ideally if the app is in this mode, we also restrict their ability to transfer Hotspot (either all together, or to the allowed account address for payments).

Otherwise, this feature seems easy to work around and is not really secure in its intended implementation. Would like your thoughts on this.

2021-09-17 00:37 UTC, tyler-whitman approved these changes
Code looks good and it works as expected. I didn't get to test everything, but it looks like payment / QR is working as expected still and disabled properly when in deploy mode. I did find one UI glitch, when you enter allowed account addresses when enabling deploy mode on iOS the text shifts out of the modal container.
@cokes518 if you are ok with it code looks good. Maybe @matthewcarlreetz wants to take another look at the code before we merge it

2021-09-17 01:00 UTC, tyler-whitman requested changes

2021-09-17 01:00 UTC, tyler-whitman commented on src/features/moreTab/more/MoreListItem.tsx
> +  let textColor = 'primaryText'
This needs a type to fix lint errors:

` let textColor: Colors = 'primaryText'`

2021-09-20 19:41 UTC, tyler-whitman commented
Closed with https://github.com/helium/hotspot-app/pull/948

2021-09-20 19:41 UTC, closed without merging