Add Linxdot Hotspot
helium/hotspot-app pull request #820
Opened 2021-07-22 13:24 UTC by eriks12

This is to add the Linxdot to the hotspot app. The only thing that needs changing is the onboarding ID in src/makers/linxdot/index.ts, which I'll be in talks with DeWi for. Please let me know if any changes are needed.

2021-07-22 20:02 UTC, cokes518 requested changes

2021-07-22 20:02 UTC, cokes518 commented on src/makers/linxdot/hotspots.ts
> +        '<b><white>Diagnostic support allows Linxdot to identify issues with your Hotspot in a secure way.</white></b>\n\nLinxdotwill never have access to private keys and will only ever be able to a
```suggestion
        '<b><white>Diagnostic support allows Linxdot to identify issues with your Hotspot in a secure way.</white></b>\n\nLinxdot will never have access to private keys and will only ever be able to access your Hotspot and not any other devices on your Network.\n\nIf you would like to opt-out of diagnostic support please email <purple><b>support@linxdot.com</b></purple> from the email used to purchase the Hotspot.',
```

2021-07-22 20:03 UTC, cokes518 commented
this is good to merge (copy-wise)

2021-07-23 20:13 UTC, cokes518 commented
cc @tyler-whitman this is good to merge as well.

2021-07-24 01:02 UTC, tyler-whitman requested changes

2021-07-24 01:02 UTC, tyler-whitman commented on src/makers/linxdot/index.ts
> +  id: 99999, // TODO: Get maker id from onboarding server
Pending approved maker id

2021-07-26 17:19 UTC, cokes518 commented
Hi @eriks12 as we await the MOC approval, please let me know the name you'd like to appear in the Onboarding server, and how many location asserts you'd like to include (minimum is 1).

Here is an example of other Makers and the names they use.
https://onboarding.dewi.org/api/v2/makers

2021-07-26 17:39 UTC, eriks12 commented
> Hi @eriks12 as we await the MOC approval, please let me know the name you'd like to appear in the Onboarding server, and how many location asserts you'd like to include (minimum is 1).
> 
> Here is an example of other Makers and the names they use.
> https://onboarding.dewi.org/api/v2/makers

Hi, thanks for getting in touch! We’re happy with “Linxdot” as the name on the onboarding server. 10 location asserts is fine to begin with, and we’ll fund our maker account additionally once it’s created. 

Many thanks.
-Erik

2021-07-26 17:40 UTC, cokes518 commented
Hi Erik, are you sure you want to pay for each user's assert_location transactions, up to 10? That's $100 in assert fees per user.

2021-07-26 17:42 UTC, eriks12 commented
> Hi Erik, are you sure you want to pay for each user's assert_location transactions, up to 10? That's $100 in assert fees per user.

Sorry, I misunderstood. 1 included location assert only :).

I thought this was about initial funding of a maker account.

2021-08-02 17:52 UTC, cokes518 approved these changes
maker account created
```{
    "code": 200,
    "data": {
        "id": 15,
        "name": "Linxdot",
        "address": "14eUfY1GsjK4WH6uZYoeagnFtigBKdvPruAXLmc5UsUMEDj3yib",
        "locationNonceLimit": 1
    },
    "success": true
}```

2021-08-02 17:52 UTC, cokes518 commented on src/makers/linxdot/index.ts
> +  id: 99999, // TODO: Get maker id from onboarding server
```suggestion
  id: 15,
```

2021-08-02 19:10 UTC, tyler-whitman approved these changes

2021-08-02 19:13 UTC, merged