Add Dragino hotspot HP0D
helium/hotspot-app pull request #956
Opened 2021-09-27 02:30 UTC by dragino

2021-10-01 22:10 UTC, Sophi commented
Hello, if you are trying to make a HIP19 proposal, we have moved to a [new repo here](https://github.com/dewi-alliance/hotspot-manufacturers#readme). I'm going to close this request.

2021-11-28 17:43 UTC, Dany8921 approved these changes

2022-01-18 20:03 UTC, tyler-whitman requested changes
Please see the above comments and resolve the merge conflicts with main.

2022-01-18 20:03 UTC, tyler-whitman commented on src/makers/dragino/index.ts
> +  id: 21, // TODO: Get maker id from onboarding server
You should be using maker id 27

2022-01-25 15:06 UTC, dragino commented on src/makers/dragino/index.ts
> +  id: 21, // TODO: Get maker id from onboarding server
Change to 27 now.

2022-01-27 15:22 UTC, closed without merging

2022-01-27 15:22 UTC, dragino commented
Will use a new PR to clean this.